from enum import Enum
from pydantic import BaseModel


class ErrorCode(str, Enum):
    """
    Error codes for the API
    """
    AIRFLOW_ERROR = 'AIRFLOW_ERROR'
    AWS_CRED_EXPIRED = 'AWS_CRED_EXPIRED'
    AWS_NOT_AVAILABLE = 'AWS_NOT_AVAILABLE'
    DATA_FILE_MISSING_FOUND = 'DATA_FILE_MISSING_FOUND'
    DATA_RESOURCE_NOT_FOUND = 'DATA_RESOURCE_NOT_FOUND'
    FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR'
    INVALID_ARCHIVE = 'INVALID_ARCHIVE'
    INVALID_DATA_RESOURCE_UID = 'INVALID_DATA_RESOURCE_UID'
    INVALID_REQUEST_ID = 'INVALID_REQUEST_ID'
    MISSING_DATA_FILE = 'MISSING_DATA_FILE'
    MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD'
    NOT_AUTHORIZED = 'NOT_AUTHORIZED'
    NOT_AUTHORIZED_FOR_DATA_RESOURCE = 'NOT_AUTHORIZED_FOR_DATA_RESOURCE'
    REGISTRY_ERROR = 'REGISTRY_ERROR'
    SYSTEM_ERROR = 'SYSTEM_ERROR'
    UNRECOGNISED_LICENCE = 'UNRECOGNISED_LICENCE'
    UNSUPPORTED_CORE_TYPE = 'UNSUPPORTED_CORE_TYPE'
